import type { Account, CompanySettings } from "@/lib/types";

export const DEFAULT_EXPENSE_CATEGORIES = [
  "Software & SaaS",
  "Cloud Infrastructure",
  "Payroll & Contractors",
  "Marketing",
  "Travel",
  "Office",
  "Professional Services",
  "Bank Fees",
  "Tax & Compliance",
];

export const DEFAULT_INCOME_CATEGORIES = [
  "Software Development",
  "Retainers",
  "Support",
  "Consulting",
  "Licensing",
];

export const DEFAULT_DEPARTMENTS = [
  "Engineering",
  "Operations",
  "Sales",
  "Finance",
  "Leadership",
];

export const DEFAULT_PROJECTS_CLIENTS = [
  "Internal",
  "Client Delivery",
  "Support Retainers",
];

export const DEFAULT_SETTINGS: CompanySettings = {
  id: 1,
  company_name: "Stratus Software Solutions",
  vat_rate: 15,
  default_currency: "ZAR",
  expense_categories: DEFAULT_EXPENSE_CATEGORIES,
  income_categories: DEFAULT_INCOME_CATEGORIES,
  departments: DEFAULT_DEPARTMENTS,
  projects_clients: DEFAULT_PROJECTS_CLIENTS,
};

export const DEFAULT_ACCOUNTS: Account[] = [
  {
    id: "default-1010",
    code: "1010",
    name: "Cash at Bank",
    account_type: "asset",
    normal_balance: "debit",
    parent_account_id: null,
    description: "Primary operating bank account.",
    is_active: true,
    is_system: true,
    sort_order: 1010,
  },
  {
    id: "default-1100",
    code: "1100",
    name: "Accounts Receivable",
    account_type: "asset",
    normal_balance: "debit",
    parent_account_id: null,
    description: "Amounts owed by clients for issued invoices.",
    is_active: true,
    is_system: true,
    sort_order: 1100,
  },
  {
    id: "default-2010",
    code: "2010",
    name: "Accounts Payable",
    account_type: "liability",
    normal_balance: "credit",
    parent_account_id: null,
    description: "Supplier bills and unpaid expenses.",
    is_active: true,
    is_system: true,
    sort_order: 2010,
  },
  {
    id: "default-4100",
    code: "4100",
    name: "Subscription Revenue",
    account_type: "income",
    normal_balance: "credit",
    parent_account_id: null,
    description: "Recurring SaaS and support subscription revenue.",
    is_active: true,
    is_system: true,
    sort_order: 4100,
  },
  {
    id: "default-4200",
    code: "4200",
    name: "Integration Services Revenue",
    account_type: "income",
    normal_balance: "credit",
    parent_account_id: null,
    description: "Implementation, automation, and integration services revenue.",
    is_active: true,
    is_system: true,
    sort_order: 4200,
  },
  {
    id: "default-5010",
    code: "5010",
    name: "Hardware Cost of Sales",
    account_type: "cost_of_sales",
    normal_balance: "debit",
    parent_account_id: null,
    description: "Direct hardware costs for client projects.",
    is_active: true,
    is_system: true,
    sort_order: 5010,
  },
  {
    id: "default-6010",
    code: "6010",
    name: "Software Subscriptions",
    account_type: "expense",
    normal_balance: "debit",
    parent_account_id: null,
    description: "Internal SaaS tools and subscriptions.",
    is_active: true,
    is_system: true,
    sort_order: 6010,
  },
  {
    id: "default-6100",
    code: "6100",
    name: "Cloud Infrastructure",
    account_type: "expense",
    normal_balance: "debit",
    parent_account_id: null,
    description: "Hosting, cloud, database, and infrastructure costs.",
    is_active: true,
    is_system: true,
    sort_order: 6100,
  },
];
